version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/chells-kitchen
      - socket-data:/tmp/mysql.sock
      - socket-database:/tmp/sockets/puma.sock
    depends_on:
      - db
  db:
    build: ./environments
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - ./tmp/db:/var/lib/mysql
      - socket-data:/tmp/mysql.sock
    command: mysql -u root -p -e"$(cat db/grant_user.sql)"
  web:
    build:
      context: containers/nginx
    volumes:
      - .:/chells-kitchen
      - socket-database:/tmp/sockets/puma.sock
    ports:
      - 80:80
    depends_on:
      - app
volumes:
 socket-data:
 socket-database:
